env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:jest-dom/recommended"
  - "plugin:testing-library/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
settings:
  react:
    version: "16.13"
plugins:
  - "react"
  - "react-hooks"
  - "@typescript-eslint"
  - "jsx-a11y"
  - "testing-library"
  - "jest-dom"
rules:
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
overrides:
  - files: "*.tsx"
    rules:
      "@typescript-eslint/explicit-module-boundary-types": "off"
      "@typescript-eslint/explicit-function-return-type": "off"
      "jsx-a11y/anchor-is-valid": "off"
